title: Amber Pixie Crafts
description: > # this means to ignore newlines until "baseurl:"
  Amber Pixie Crafts, hand made in New Mills, Derbyshire.
baseurl: "" # the subpath of your site, e.g. /blog
url: https://www.amberpixiecrafts.co.uk # the base hostname & protocol for your site
# Build settings
markdown: kramdown

facebook:
  app_id: 

logo: "../css/style/img/icon-large.png"

social: 
  name: Your Facebook Page
  link: "https://www.facebook.com/amberpixiecrafts"

google_site_verification: googleXXXXXXXXXXXXXXXX.html

include: ['pages']

gems:
  - jekyll-sitemap
  - jekyll-seo-tag

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: facebook
    url: https://www.facebook.com/amberpixiecrafts
  - title: twitter
    url: https://twitter.com/amberpixiecrafts

# Build settings
markdown: kramdown
permalink: pretty